2022-05-04 13:20:54,329 INFO    MainThread:7560 [internal.py:wandb_internal():92] W&B internal server running at pid: 7560, started at: 2022-05-04 13:20:54.328618
2022-05-04 13:20:54,332 INFO    WriterThread:7560 [datastore.py:open_for_write():77] open: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220504_132053-3hn0q926\run-3hn0q926.wandb
2022-05-04 13:20:54,336 DEBUG   SenderThread:7560 [sender.py:send():235] send: header
2022-05-04 13:20:54,336 DEBUG   SenderThread:7560 [sender.py:send():235] send: run
2022-05-04 13:20:55,210 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: check_version
2022-05-04 13:20:55,211 INFO    SenderThread:7560 [dir_watcher.py:__init__():169] watching files in: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220504_132053-3hn0q926\files
2022-05-04 13:20:55,211 INFO    SenderThread:7560 [sender.py:_start_run_threads():812] run started: 3hn0q926 with start time 1651663253
2022-05-04 13:20:55,211 DEBUG   SenderThread:7560 [sender.py:send():235] send: summary
2022-05-04 13:20:55,212 INFO    SenderThread:7560 [sender.py:_save_file():947] saving file wandb-summary.json with policy end
2022-05-04 13:20:55,213 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: check_version
2022-05-04 13:20:56,140 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: run_start
2022-05-04 13:20:56,214 INFO    Thread-11 :7560 [dir_watcher.py:_on_file_created():217] file/dir created: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220504_132053-3hn0q926\files\wandb-summary.json
2022-05-04 13:20:57,257 DEBUG   HandlerThread:7560 [meta.py:__init__():37] meta init
2022-05-04 13:20:57,257 DEBUG   HandlerThread:7560 [meta.py:__init__():51] meta init done
2022-05-04 13:20:57,257 DEBUG   HandlerThread:7560 [meta.py:probe():211] probe
2022-05-04 13:20:57,341 DEBUG   HandlerThread:7560 [meta.py:_setup_git():201] setup git
2022-05-04 13:20:57,439 DEBUG   HandlerThread:7560 [meta.py:_setup_git():208] setup git done
2022-05-04 13:20:57,440 DEBUG   HandlerThread:7560 [meta.py:_save_pip():55] save pip
2022-05-04 13:20:57,441 DEBUG   HandlerThread:7560 [meta.py:_save_pip():69] save pip done
2022-05-04 13:20:57,441 DEBUG   HandlerThread:7560 [meta.py:_save_conda():76] save conda
2022-05-04 13:20:57,444 ERROR   HandlerThread:7560 [meta.py:_save_conda():85] Error saving conda packages
Traceback (most recent call last):
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\wandb\sdk\internal\meta.py", line 81, in _save_conda
    subprocess.call(
  File "C:\Users\gizem\anaconda3\envs\iw\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\gizem\anaconda3\envs\iw\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\gizem\anaconda3\envs\iw\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
2022-05-04 13:20:57,447 DEBUG   HandlerThread:7560 [meta.py:_save_conda():86] save conda done
2022-05-04 13:20:57,447 DEBUG   HandlerThread:7560 [meta.py:probe():249] probe done
2022-05-04 13:20:57,658 DEBUG   SenderThread:7560 [sender.py:send():235] send: files
2022-05-04 13:20:57,658 INFO    SenderThread:7560 [sender.py:_save_file():947] saving file wandb-metadata.json with policy now
2022-05-04 13:20:57,659 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:20:57,660 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:20:58,219 INFO    Thread-11 :7560 [dir_watcher.py:_on_file_created():217] file/dir created: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220504_132053-3hn0q926\files\output.log
2022-05-04 13:20:58,219 INFO    Thread-11 :7560 [dir_watcher.py:_on_file_created():217] file/dir created: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220504_132053-3hn0q926\files\requirements.txt
2022-05-04 13:20:58,220 INFO    Thread-11 :7560 [dir_watcher.py:_on_file_created():217] file/dir created: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220504_132053-3hn0q926\files\wandb-metadata.json
2022-05-04 13:20:58,220 INFO    Thread-11 :7560 [dir_watcher.py:_on_file_created():217] file/dir created: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220504_132053-3hn0q926\files\conda-environment.yaml
2022-05-04 13:20:58,841 DEBUG   SenderThread:7560 [sender.py:send():235] send: telemetry
2022-05-04 13:21:00,057 INFO    Thread-17 :7560 [upload_job.py:push():137] Uploaded file C:\Users\gizem\AppData\Local\Temp\tmpyr4wrehswandb\2244lf2q-wandb-metadata.json
2022-05-04 13:21:02,251 INFO    Thread-11 :7560 [dir_watcher.py:_on_file_modified():230] file/dir modified: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220504_132053-3hn0q926\files\output.log
2022-05-04 13:21:13,862 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:21:13,863 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:21:26,421 INFO    Thread-11 :7560 [dir_watcher.py:_on_file_modified():230] file/dir modified: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220504_132053-3hn0q926\files\config.yaml
2022-05-04 13:21:29,923 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:21:29,924 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:21:34,029 DEBUG   SenderThread:7560 [sender.py:send():235] send: stats
2022-05-04 13:21:46,139 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:21:46,140 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:22:01,921 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:22:01,925 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:22:13,632 DEBUG   SenderThread:7560 [sender.py:send():235] send: stats
2022-05-04 13:22:17,800 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:22:17,800 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:22:33,699 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:22:33,699 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:22:49,312 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:22:49,313 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:22:53,028 DEBUG   SenderThread:7560 [sender.py:send():235] send: stats
2022-05-04 13:23:05,444 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:23:05,444 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:23:21,253 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:23:21,253 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:23:32,597 DEBUG   SenderThread:7560 [sender.py:send():235] send: stats
2022-05-04 13:23:37,095 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:23:37,097 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:23:53,667 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:23:53,668 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:24:10,360 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:24:10,361 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:24:17,369 DEBUG   SenderThread:7560 [sender.py:send():235] send: stats
2022-05-04 13:24:27,123 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:24:27,124 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:24:43,499 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:24:43,499 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:25:00,222 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:25:00,223 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:25:05,073 DEBUG   SenderThread:7560 [sender.py:send():235] send: stats
2022-05-04 13:25:16,825 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:25:16,826 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:25:33,615 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:25:33,616 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:25:50,576 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:25:50,578 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:25:53,077 DEBUG   SenderThread:7560 [sender.py:send():235] send: stats
2022-05-04 13:26:08,081 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:26:08,082 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:26:24,773 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:26:24,773 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:26:36,491 DEBUG   SenderThread:7560 [sender.py:send():235] send: stats
2022-05-04 13:26:41,537 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:26:41,537 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:26:58,150 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:26:58,150 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:27:14,840 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:27:14,841 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:27:22,515 DEBUG   SenderThread:7560 [sender.py:send():235] send: stats
2022-05-04 13:27:32,002 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:27:32,003 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:27:52,053 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:27:53,216 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:28:07,888 DEBUG   SenderThread:7560 [sender.py:send():235] send: stats
2022-05-04 13:28:09,990 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:28:09,991 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:28:26,772 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:28:26,773 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:28:46,851 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:28:49,695 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:28:53,474 DEBUG   SenderThread:7560 [sender.py:send():235] send: stats
2022-05-04 13:29:06,491 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:29:06,492 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:29:23,069 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:29:23,070 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:29:39,797 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:29:39,798 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:29:41,944 DEBUG   SenderThread:7560 [sender.py:send():235] send: stats
2022-05-04 13:29:56,951 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:29:56,952 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:30:13,972 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:30:13,973 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:30:24,674 DEBUG   SenderThread:7560 [sender.py:send():235] send: stats
2022-05-04 13:30:30,567 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:30:30,568 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:30:47,620 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:30:47,621 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:31:04,414 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:31:04,415 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:31:24,440 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:31:37,786 ERROR   SenderThread:7560 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x0000024BE246DE10>, 'Connection to api.wandb.ai timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024BE246DE10>, 'Connection to api.wandb.ai timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\wandb\sdk\internal\internal_api.py", line 141, in execute
    return self.client.execute(*args, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\transport\requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\requests\adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024BE246DE10>, 'Connection to api.wandb.ai timed out. (connect timeout=10)'))
2022-05-04 13:31:44,472 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:31:45,587 DEBUG   SenderThread:7560 [sender.py:send():235] send: stats
2022-05-04 13:31:45,589 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:31:48,065 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:31:57,457 DEBUG   SenderThread:7560 [sender.py:send():235] send: stats
2022-05-04 13:32:04,524 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:32:04,525 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:32:21,598 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:32:21,599 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:32:41,364 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:32:41,365 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:32:44,860 DEBUG   SenderThread:7560 [sender.py:send():235] send: stats
2022-05-04 13:32:59,867 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:32:59,868 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:33:13,110 ERROR   SenderThread:7560 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\gizem\anaconda3\envs\iw\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000024BE246F670>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024BE246F670>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\wandb\sdk\internal\internal_api.py", line 141, in execute
    return self.client.execute(*args, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\transport\requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\gizem\anaconda3\envs\iw\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024BE246F670>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-05-04 13:33:19,891 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:33:39,950 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:33:49,418 WARNING FileStreamThread:7560 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000024BE119EF20>>, args: ('https://api.wandb.ai/files/sml-eth/noisy-fair/3hn0q926/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 15, 'content': ['{"system.gpu.0.gpu": 0.0, "system.gpu.0.memory": 0.0, "system.gpu.0.memoryAllocated": 3.22, "system.gpu.0.temp": 74.0, "system.cpu": 100.0, "system.memory": 85.75, "system.disk": 86.9, "system.proc.memory.availableMB": 2314.05, "system.proc.memory.rssMB": 29.44, "system.proc.memory.percent": 0.18, "system.proc.cpu.threads": 25.53, "system.network.sent": 1866702, "system.network.recv": 4249486, "_wandb": true, "_timestamp": 1651663963, "_runtime": 710}']}}, 'dropped': 0}}
2022-05-04 13:33:51,633 WARNING FileStreamThread:7560 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/sml-eth/noisy-fair/3hn0q926/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024BE246CC40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000024BE119EF20>>, args: ('https://api.wandb.ai/files/sml-eth/noisy-fair/3hn0q926/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 15, 'content': ['{"system.gpu.0.gpu": 0.0, "system.gpu.0.memory": 0.0, "system.gpu.0.memoryAllocated": 3.22, "system.gpu.0.temp": 74.0, "system.cpu": 100.0, "system.memory": 85.75, "system.disk": 86.9, "system.proc.memory.availableMB": 2314.05, "system.proc.memory.rssMB": 29.44, "system.proc.memory.percent": 0.18, "system.proc.cpu.threads": 25.53, "system.network.sent": 1866702, "system.network.recv": 4249486, "_wandb": true, "_timestamp": 1651663963, "_runtime": 710}']}}, 'dropped': 0}}
2022-05-04 13:33:56,576 WARNING FileStreamThread:7560 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/sml-eth/noisy-fair/3hn0q926/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024BE246E650>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000024BE119EF20>>, args: ('https://api.wandb.ai/files/sml-eth/noisy-fair/3hn0q926/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 15, 'content': ['{"system.gpu.0.gpu": 0.0, "system.gpu.0.memory": 0.0, "system.gpu.0.memoryAllocated": 3.22, "system.gpu.0.temp": 74.0, "system.cpu": 100.0, "system.memory": 85.75, "system.disk": 86.9, "system.proc.memory.availableMB": 2314.05, "system.proc.memory.rssMB": 29.44, "system.proc.memory.percent": 0.18, "system.proc.cpu.threads": 25.53, "system.network.sent": 1866702, "system.network.recv": 4249486, "_wandb": true, "_timestamp": 1651663963, "_runtime": 710}']}}, 'dropped': 0}}
2022-05-04 13:33:59,989 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:34:06,211 WARNING FileStreamThread:7560 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/sml-eth/noisy-fair/3hn0q926/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024BE246D6C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000024BE119EF20>>, args: ('https://api.wandb.ai/files/sml-eth/noisy-fair/3hn0q926/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 15, 'content': ['{"system.gpu.0.gpu": 0.0, "system.gpu.0.memory": 0.0, "system.gpu.0.memoryAllocated": 3.22, "system.gpu.0.temp": 74.0, "system.cpu": 100.0, "system.memory": 85.75, "system.disk": 86.9, "system.proc.memory.availableMB": 2314.05, "system.proc.memory.rssMB": 29.44, "system.proc.memory.percent": 0.18, "system.proc.cpu.threads": 25.53, "system.network.sent": 1866702, "system.network.recv": 4249486, "_wandb": true, "_timestamp": 1651663963, "_runtime": 710}']}}, 'dropped': 0}}
2022-05-04 13:34:20,009 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:34:25,237 WARNING FileStreamThread:7560 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/sml-eth/noisy-fair/3hn0q926/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024BE246D570>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000024BE119EF20>>, args: ('https://api.wandb.ai/files/sml-eth/noisy-fair/3hn0q926/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 15, 'content': ['{"system.gpu.0.gpu": 0.0, "system.gpu.0.memory": 0.0, "system.gpu.0.memoryAllocated": 3.22, "system.gpu.0.temp": 74.0, "system.cpu": 100.0, "system.memory": 85.75, "system.disk": 86.9, "system.proc.memory.availableMB": 2314.05, "system.proc.memory.rssMB": 29.44, "system.proc.memory.percent": 0.18, "system.proc.cpu.threads": 25.53, "system.network.sent": 1866702, "system.network.recv": 4249486, "_wandb": true, "_timestamp": 1651663963, "_runtime": 710}']}}, 'dropped': 0}}
2022-05-04 13:35:03,884 WARNING FileStreamThread:7560 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/sml-eth/noisy-fair/3hn0q926/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024BE246D090>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000024BE119EF20>>, args: ('https://api.wandb.ai/files/sml-eth/noisy-fair/3hn0q926/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 15, 'content': ['{"system.gpu.0.gpu": 0.0, "system.gpu.0.memory": 0.0, "system.gpu.0.memoryAllocated": 3.22, "system.gpu.0.temp": 74.0, "system.cpu": 100.0, "system.memory": 85.75, "system.disk": 86.9, "system.proc.memory.availableMB": 2314.05, "system.proc.memory.rssMB": 29.44, "system.proc.memory.percent": 0.18, "system.proc.cpu.threads": 25.53, "system.network.sent": 1866702, "system.network.recv": 4249486, "_wandb": true, "_timestamp": 1651663963, "_runtime": 710}']}}, 'dropped': 0}}
2022-05-04 13:35:27,378 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:35:47,379 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:36:07,401 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:36:15,497 WARNING FileStreamThread:7560 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/sml-eth/noisy-fair/3hn0q926/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024BE246F940>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000024BE119EF20>>, args: ('https://api.wandb.ai/files/sml-eth/noisy-fair/3hn0q926/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 15, 'content': ['{"system.gpu.0.gpu": 0.0, "system.gpu.0.memory": 0.0, "system.gpu.0.memoryAllocated": 3.22, "system.gpu.0.temp": 74.0, "system.cpu": 100.0, "system.memory": 85.75, "system.disk": 86.9, "system.proc.memory.availableMB": 2314.05, "system.proc.memory.rssMB": 29.44, "system.proc.memory.percent": 0.18, "system.proc.cpu.threads": 25.53, "system.network.sent": 1866702, "system.network.recv": 4249486, "_wandb": true, "_timestamp": 1651663963, "_runtime": 710}']}}, 'dropped': 0}}
2022-05-04 13:36:27,814 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:36:47,460 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:37:07,487 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:37:27,507 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:37:47,517 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:38:07,532 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:38:27,601 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:38:28,117 WARNING FileStreamThread:7560 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/sml-eth/noisy-fair/3hn0q926/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024BE246E140>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000024BE119EF20>>, args: ('https://api.wandb.ai/files/sml-eth/noisy-fair/3hn0q926/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 15, 'content': ['{"system.gpu.0.gpu": 0.0, "system.gpu.0.memory": 0.0, "system.gpu.0.memoryAllocated": 3.22, "system.gpu.0.temp": 74.0, "system.cpu": 100.0, "system.memory": 85.75, "system.disk": 86.9, "system.proc.memory.availableMB": 2314.05, "system.proc.memory.rssMB": 29.44, "system.proc.memory.percent": 0.18, "system.proc.cpu.threads": 25.53, "system.network.sent": 1866702, "system.network.recv": 4249486, "_wandb": true, "_timestamp": 1651663963, "_runtime": 710}']}}, 'dropped': 0}}
2022-05-04 13:38:47,619 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:39:07,645 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:39:27,663 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:39:47,698 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:40:07,744 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:40:27,774 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:40:47,810 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:41:07,837 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:41:27,859 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:41:47,960 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:42:07,984 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:42:28,077 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:42:48,109 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:43:08,302 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:43:28,362 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:43:48,359 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:44:02,007 WARNING FileStreamThread:7560 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/sml-eth/noisy-fair/3hn0q926/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024BE246D570>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000024BE119EF20>>, args: ('https://api.wandb.ai/files/sml-eth/noisy-fair/3hn0q926/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-05-04 13:44:04,462 WARNING FileStreamThread:7560 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/sml-eth/noisy-fair/3hn0q926/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024BE246DFC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000024BE119EF20>>, args: ('https://api.wandb.ai/files/sml-eth/noisy-fair/3hn0q926/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-05-04 13:44:08,437 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:44:28,525 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:44:48,559 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:45:08,597 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:45:28,622 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:45:48,678 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:46:05,057 WARNING MainThread:7560 [internal.py:wandb_internal():155] Internal process interrupt: 1
2022-05-04 13:46:08,715 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:46:28,787 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:46:48,871 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:47:08,882 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:47:28,925 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:47:48,949 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:47:56,302 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:47:57,692 DEBUG   SenderThread:7560 [sender.py:send():235] send: stats
2022-05-04 13:47:57,694 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:47:59,253 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:48:00,867 DEBUG   SenderThread:7560 [sender.py:send():235] send: stats
2022-05-04 13:48:00,868 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:48:02,725 DEBUG   SenderThread:7560 [sender.py:send():235] send: stats
2022-05-04 13:48:02,727 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:48:04,289 DEBUG   SenderThread:7560 [sender.py:send():235] send: stats
2022-05-04 13:48:04,290 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:48:06,089 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:48:07,624 DEBUG   SenderThread:7560 [sender.py:send():235] send: stats
2022-05-04 13:48:07,625 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:48:08,986 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: stop_status
2022-05-04 13:48:09,285 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:48:11,114 DEBUG   SenderThread:7560 [sender.py:send():235] send: stats
2022-05-04 13:48:11,116 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:48:12,643 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:48:14,267 DEBUG   SenderThread:7560 [sender.py:send():235] send: stats
2022-05-04 13:48:14,269 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:48:15,835 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:48:16,632 DEBUG   SenderThread:7560 [sender.py:send():235] send: stats
2022-05-04 13:48:16,633 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:48:17,458 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:48:17,765 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: poll_exit
2022-05-04 13:48:18,272 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:48:18,616 INFO    Thread-11 :7560 [dir_watcher.py:_on_file_modified():230] file/dir modified: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220504_132053-3hn0q926\files\output.log
2022-05-04 13:48:19,264 DEBUG   SenderThread:7560 [sender.py:send():235] send: stats
2022-05-04 13:48:19,265 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:48:20,103 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:48:21,133 DEBUG   SenderThread:7560 [sender.py:send():235] send: stats
2022-05-04 13:48:21,149 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:48:22,166 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:48:22,874 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: poll_exit
2022-05-04 13:48:22,982 DEBUG   SenderThread:7560 [sender.py:send():235] send: stats
2022-05-04 13:48:22,982 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:48:23,722 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:48:24,418 DEBUG   SenderThread:7560 [sender.py:send():235] send: stats
2022-05-04 13:48:24,419 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:48:25,131 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:48:26,272 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:48:27,179 DEBUG   SenderThread:7560 [sender.py:send():235] send: stats
2022-05-04 13:48:27,179 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:48:27,726 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:48:27,978 DEBUG   HandlerThread:7560 [handler.py:handle_request():141] handle_request: poll_exit
2022-05-04 13:48:28,421 DEBUG   SenderThread:7560 [sender.py:send():235] send: stats
2022-05-04 13:48:28,423 DEBUG   SenderThread:7560 [sender.py:send_request():249] send_request: stop_status
2022-05-04 13:48:28,555 WARNING MainThread:7560 [internal.py:wandb_internal():155] Internal process interrupt: 2
2022-05-04 13:48:28,557 ERROR   MainThread:7560 [internal.py:wandb_internal():158] Internal process interrupted.
2022-05-04 13:48:28,628 INFO    WriterThread:7560 [datastore.py:close():281] close: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220504_132053-3hn0q926\run-3hn0q926.wandb
2022-05-04 13:48:28,983 INFO    HandlerThread:7560 [handler.py:finish():790] shutting down handler
2022-05-04 13:48:29,637 INFO    SenderThread:7560 [sender.py:finish():1107] shutting down sender
2022-05-04 13:48:29,637 INFO    SenderThread:7560 [dir_watcher.py:finish():283] shutting down directory watcher
2022-05-04 13:48:29,717 INFO    SenderThread:7560 [dir_watcher.py:finish():313] scan: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220504_132053-3hn0q926\files
2022-05-04 13:48:29,718 INFO    SenderThread:7560 [dir_watcher.py:finish():327] scan save: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220504_132053-3hn0q926\files\conda-environment.yaml conda-environment.yaml
2022-05-04 13:48:29,719 INFO    SenderThread:7560 [dir_watcher.py:finish():327] scan save: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220504_132053-3hn0q926\files\config.yaml config.yaml
2022-05-04 13:48:29,721 INFO    SenderThread:7560 [dir_watcher.py:finish():327] scan save: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220504_132053-3hn0q926\files\output.log output.log
2022-05-04 13:48:29,724 INFO    SenderThread:7560 [dir_watcher.py:finish():327] scan save: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220504_132053-3hn0q926\files\requirements.txt requirements.txt
2022-05-04 13:48:29,743 INFO    SenderThread:7560 [dir_watcher.py:finish():327] scan save: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220504_132053-3hn0q926\files\wandb-metadata.json wandb-metadata.json
2022-05-04 13:48:29,773 INFO    SenderThread:7560 [dir_watcher.py:finish():327] scan save: C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220504_132053-3hn0q926\files\wandb-summary.json wandb-summary.json
2022-05-04 13:48:29,775 INFO    SenderThread:7560 [file_pusher.py:finish():145] shutting down file pusher
2022-05-04 13:48:29,776 INFO    SenderThread:7560 [file_pusher.py:join():150] waiting for file pusher
2022-05-04 13:48:32,816 INFO    Thread-21 :7560 [upload_job.py:push():137] Uploaded file C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220504_132053-3hn0q926\files\wandb-summary.json
2022-05-04 13:48:32,817 INFO    Thread-20 :7560 [upload_job.py:push():137] Uploaded file C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220504_132053-3hn0q926\files\requirements.txt
2022-05-04 13:48:32,821 INFO    Thread-18 :7560 [upload_job.py:push():137] Uploaded file C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220504_132053-3hn0q926\files\config.yaml
2022-05-04 13:48:32,832 INFO    Thread-19 :7560 [upload_job.py:push():137] Uploaded file C:\Users\gizem\Documents\GitHub\noisy_fair\wandb\run-20220504_132053-3hn0q926\files\output.log
2022-05-04 13:48:33,967 INFO    MainThread:7560 [internal.py:handle_exit():82] Internal process exited
